/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.nokia.tools.s60ct.model.confml.validation;

import com.nokia.tools.s60ct.model.confml.EResourceKind;
import com.nokia.tools.s60ct.model.confml.ESetting;

/**
 * A sample validator interface for {@link com.nokia.tools.s60ct.model.confml.EResourceSetting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EResourceSettingValidator {
	boolean validate();

	boolean validateKind(EResourceKind value);
	boolean validateLocalPath(ESetting value);
	boolean validateTargetPath(ESetting value);
}
