/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.nokia.tools.s60ct.model.confml.validation;

import com.nokia.tools.s60ct.model.confml.EItemSetting;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.nokia.tools.s60ct.model.confml.ESequenceSetting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ESequenceSettingValidator {
	boolean validate();

	boolean validateMinOccurs(Integer value);
	boolean validateMaxOccurs(Integer value);
	boolean validateItems(EList<EItemSetting> value);
	boolean validateTemplate(EItemSetting value);
	boolean validateMapKey(String value);
	boolean validateMapValue(String value);

	boolean validateVisibleSubSettings(EList<String> value);
}
