/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.nokia.tools.s60ct.model.confml.validation;

import com.nokia.tools.s60ct.model.confml.EProperty;
import com.nokia.tools.s60ct.model.confml.ESetting;
import com.nokia.tools.s60ct.model.confml.ESettingValue;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link com.nokia.tools.s60ct.model.confml.ESetting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ESettingValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateRef(String value);
	boolean validateRfs(Boolean value);
	boolean validateValue(ESettingValue value);
	boolean validateDefaultValue(ESettingValue value);
	boolean validateDefaultRfs(Boolean value);
	boolean validateReadOnly(boolean value);
	boolean validateConstraint(String value);
	boolean validateRelevant(String value);
	boolean validateRequired(boolean value);
	boolean validateProperties(EList<EProperty> value);
	boolean validateDeprecated(boolean value);
	boolean validateModified(boolean value);
	boolean validateSetdefault(boolean value);
	boolean validateComputedRelevant(boolean value);
	boolean validateComputedConstraint(boolean value);
	boolean validateRelevantAST(Object value);
	boolean validateConstraintAST(Object value);
	boolean validateDependencies(EList<EObject> value);
	boolean validateOptionDependencies(EList<ESetting> value);
	boolean validateValueNull(boolean value);

	boolean validateNotes(String value);
}
