<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="errormodel"
    nsURI="http://www.nokia.com/xml/ns/cpf-views/errors" nsPrefix="com.nokia.tools.variant.views.errormodel">
  <eClassifiers xsi:type="ecore:EClass" name="ErrorsRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="errors" upperBound="-1"
        eType="#//Error" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Error">
    <eStructuralFeatures xsi:type="ecore:EReference" name="setting" eType="ecore:EClass confml.ecore#//Setting"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
