/*
 * Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
 * All rights reserved.
 * This component and the accompanying materials are made available
 * under the terms of "Eclipse Public License v1.0"
 * which accompanies this distribution, and is available
 * at the URL "http://www.eclipse.org/legal/epl-v10.html".
 * 
 * Initial Contributors:
 * Nokia Corporation - Initial contribution
 * 
 * Contributors:
 * 
 * Description: This file is part of com.nokia.tools.vct.crml component.
 */

package com.nokia.tools.vct.crml.crmodel.validation;

import org.eclipse.emf.common.util.EList;

import com.nokia.tools.vct.crml.crmodel.EKey;

/**
 * A sample validator interface for {@link com.nokia.tools.vct.crml.crmodel.EKeyRange}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EKeyRangeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateInt(String value);
	boolean validateFirstInt(String value);
	boolean validateLastInt(String value);
	boolean validateIndexBits(String value);
	boolean validateFirstIndex(String value);
	boolean validateCountInt(String value);
	boolean validateKeys(EList<EKey> value);
}
