/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.nokia.tools.carbide.ct.confml.model.xsd.validation;

/**
 * A sample validator interface for {@link com.nokia.tools.carbide.ct.confml.model.xsd.EMaxInclusive}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EMaxInclusiveValidator {
	boolean validate();

}
