<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cenrep"
    nsURI="http:///cenrep.ecore" nsPrefix="cenrep">
  <eClassifiers xsi:type="ecore:EClass" name="CommonAttrs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meta" eSuperTypes="#//CommonAttrs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identification" lowerBound="1"
        eType="#//Identification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="date" lowerBound="1" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
        eType="#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editor" lowerBound="1"
        eType="#//Editor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" lowerBound="1"
        eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        eType="#//Product"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="release" lowerBound="1"
        eType="#//Release"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identification" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Owner" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Editor" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Status" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Version" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Platform" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Release" eSuperTypes="#//Content"/>
  <eClassifiers xsi:type="ecore:EClass" name="Content" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//AttributeAndDescription #//IAccessable #//IBackup">
    <eOperations name="canGenerate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uidName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uidValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialisationFileVersion"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rfs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" upperBound="-1" eType="#//Key"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="meta" eType="#//Meta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simpleKeys" upperBound="-1"
        eType="#//Key" changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bitmaskKeys" upperBound="-1"
        eType="#//Key" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangeKey" upperBound="-1"
        eType="#//KeyRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="problems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key" eSuperTypes="#//AttributeAndDescription #//RVG #//IReadOnly #//IAccessable #//IBackup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Value" upperBound="-1"
        eType="#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bits" upperBound="-1" eType="#//Bit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bitmaskKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortIdent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hexFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyRange" eSuperTypes="#//AttributeAndDescription #//RVG #//IReadOnly #//IAccessable #//IBackup">
    <eOperations name="getGKeys">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//Key"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexBits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="countInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//Key"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access" eSuperTypes="#//AttributeAndDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ACCESS_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capabilities" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Content">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bit" eSuperTypes="#//Content #//RVG">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RVG" abstract="true" interface="true">
    <eOperations name="canGenerate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="setGConf">
      <eParameters name="confName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setPriority">
      <eParameters name="prio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getGPriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gvalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rfs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TYPE">
    <eLiterals name="int"/>
    <eLiterals name="real" value="1"/>
    <eLiterals name="string" value="2"/>
    <eLiterals name="string8" value="3"/>
    <eLiterals name="binary" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ACCESS_TYPE">
    <eLiterals name="ND"/>
    <eLiterals name="READ" value="1" literal="R"/>
    <eLiterals name="WRITE" value="2" literal="W"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeAndDescription" abstract="true"
      eSuperTypes="#//CommonAttrs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IReadOnly" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAccessable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Access" upperBound="-1"
        eType="#//Access" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readAccess" eType="#//Access"
        volatile="true" transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writeAccess" eType="#//Access"
        volatile="true" transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBackup" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
