/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.nokia.tools.carbide.ct.confml.model.confml1.validation;

import com.nokia.tools.carbide.ct.confml.model.confml1.EMetaContent;

import com.nokia.tools.carbide.ct.confml.model.metaext.EConfigurationPropertyElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.nokia.tools.carbide.ct.confml.model.confml1.EMetaElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EMetaElementValidator {
	boolean validate();

	boolean validateId(EList<EMetaContent> value);

	boolean validateDate(EList<EMetaContent> value);

	boolean validateOwner(EList<EMetaContent> value);

	boolean validateEditor(EList<EMetaContent> value);

	boolean validateProduct(EList<EMetaContent> value);

	boolean validateStatus(EList<EMetaContent> value);

	boolean validatePlatform(EList<EMetaContent> value);

	boolean validateVersion(EList<EMetaContent> value);

	boolean validateRelease(EList<EMetaContent> value);

	boolean validateCustomer(EList<EMetaContent> value);

	boolean validateConfigurationProperty(
			EList<EConfigurationPropertyElement> value);
}
